# Generated by Django 5.2.3 on 2025-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0002_task_category_task_price_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='task_pictures/'),
        ),
    ]
