# Generated by Django 5.2.3 on 2025-06-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0004_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('specific_services', models.JSONField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('expertise_level', models.CharField(max_length=50)),
                ('years_of_experience', models.IntegerField()),
                ('client_present', models.CharField(max_length=50)),
                ('use_tools', models.CharField(max_length=50)),
                ('trial_session', models.CharField(max_length=50)),
                ('late_arrival', models.CharField(max_length=50)),
                ('same_day_cancel', models.CharField(max_length=50)),
                ('rescheduling', models.CharField(max_length=50)),
                ('partial_payment', models.CharField(max_length=50)),
                ('inspection', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bulk_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_slots', models.JSONField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='listing_covers/')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_signup.expert')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user_signup.service'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.service'),
        ),
        migrations.AlterField(
            model_name='review',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_signup.service'),
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_work_images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='user_signup.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
