# Generated by Django 5.2.3 on 2025-07-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0005_service_alter_booking_task_alter_payment_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='selected_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
