# Generated by Django 5.2.3 on 2025-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0007_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('reject', 'Reject')], default='pending', max_length=50),
        ),
    ]
